# Generated by Django 3.1.7 on 2021-05-11 07:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=200)),
                ('data_sprzedazy', models.DateField(verbose_name='Data sprzedaży')),
                ('data_wystawienia', models.DateField(verbose_name='Data wystawienia')),
                ('is_oplacona', models.BooleanField(default=False)),
                ('is_kosztowa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('adres', models.TextField()),
                ('taxid', models.CharField(blank=True, max_length=20, null=True)),
                ('is_sprzedawca', models.BooleanField(default=False)),
                ('is_nabywca', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Sprzedawcy',
            },
        ),
        migrations.CreateModel(
            name='JednostaMiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NumeracjaFaktur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('wzorzec', models.CharField(help_text='We wzorcu używaj znaczników: {r},{m},{d},{n} do wartości rok, miesiąc, dzień, numer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StawkaPodatku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20, unique=True)),
                ('stawka', models.DecimalField(decimal_places=2, default=0, max_digits=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaFaktury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('ilosc', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=20)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wartosc_netto', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakir.faktura')),
                ('jm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakir.jednostamiary')),
                ('stawka_podatku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakir.stawkapodatku')),
            ],
        ),
        migrations.CreateModel(
            name='LicznikFaktur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('r', models.PositiveBigIntegerField(default=0)),
                ('m', models.PositiveBigIntegerField(default=0)),
                ('d', models.PositiveBigIntegerField(default=0)),
                ('n', models.PositiveBigIntegerField(default=0)),
                ('numeracja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licznik_set', to='fakir.numeracjafaktur')),
            ],
        ),
        migrations.AddField(
            model_name='faktura',
            name='licznik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakir.licznikfaktur'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='nabywca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabywcy_set', to='fakir.firma'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='sprzedawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprzedawcy_set', to='fakir.firma'),
        ),
    ]
