# Generated by Django 3.2 on 2021-05-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.DateTimeField(verbose_name='Data wystawienia')),
                ('kupujący', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakir.kupujacy')),
                ('sprzedawca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakir.sprzedawca')),
            ],
        ),
    ]
