# Generated by Django 3.1.7 on 2021-05-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licznikfaktur',
            name='nazwa',
        ),
    ]
