# Generated by Django 3.1.7 on 2021-03-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakup',
            name='nazwa_produktu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='zakup',
            name='rodzaj_zaplaty',
            field=models.BooleanField(choices=[(1, 'ratalny'), (2, 'jednorazowy')]),
        ),
    ]