# Generated by Django 3.1.7 on 2021-03-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0002_auto_20210310_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakup',
            name='rodzaj_zaplaty',
            field=models.BooleanField(choices=[(0, 'ratalny'), (1, 'jednorazowy')], default=''),
        ),
    ]
