# Generated by Django 3.2 on 2021-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0002_faktura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faktura',
            options={'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterModelOptions(
            name='kupujacy',
            options={'verbose_name': 'Kupujący', 'verbose_name_plural': 'Kupujący'},
        ),
        migrations.AlterModelOptions(
            name='sprzedawca',
            options={'verbose_name': 'Sprzedawca', 'verbose_name_plural': 'Sprzedawcy'},
        ),
        migrations.AddField(
            model_name='faktura',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
