# Generated by Django 3.1.7 on 2021-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0003_remove_licznik_add_numeracja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='numer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
