# Generated by Django 3.2 on 2021-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0003_auto_20210507_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzedawca',
            name='PESEL',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
