# Generated by Django 3.2 on 2021-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0004_sprzedawca_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprzedawca',
            name='PESEL',
        ),
        migrations.AddField(
            model_name='kupujacy',
            name='PESEL',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
