# Generated by Django 3.2 on 2021-05-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0005_auto_20210520_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='nabywca_nazwa',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='sprzedawca_nazwa',
        ),
    ]
