# Generated by Django 3.2 on 2021-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0005_auto_20210507_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzedawca',
            name='NIP',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='PESEL',
            field=models.DecimalField(decimal_places=0, default=10000000000, max_digits=11),
        ),
    ]
