# Generated by Django 3.2.3 on 2021-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0006_auto_20210520_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontoBankowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=26)),
            ],
        ),
    ]
