# Generated by Django 3.2.2 on 2021-05-10 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0006_auto_20210507_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='data_wystawienia',
        ),
        migrations.AddField(
            model_name='faktura',
            name='J_M',
            field=models.CharField(choices=[('1', 'Godzina'), ('2', 'Sztuka')], default='1', max_length=200, verbose_name='J.N'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='Nazwa_towaru_uslugi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faktura',
            name='ilosc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faktura',
            name='podatek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faktura',
            name='wartosc_brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='faktura',
            name='wartosc_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='kupujacy',
            name='NIP',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='kupujacy',
            name='nazwa_firmy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sprzedawca',
            name='nazwa_firmy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='PESEL',
            field=models.CharField(default=10000000000, max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='adres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='imie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='nazwisko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='NIP',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='adres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='imie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='nazwisko',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
