# Generated by Django 3.2.3 on 2021-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0007_kontobankowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontobankowe',
            name='iban',
            field=models.CharField(default=432, max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kontobankowe',
            name='swift',
            field=models.CharField(default=23, max_length=11),
            preserve_default=False,
        ),
    ]
