# Generated by Django 3.2.2 on 2021-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0007_auto_20210510_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='data_wystawienia',
            field=models.DateTimeField(null=True, verbose_name='Data wystawienia'),
        ),
    ]
