# Generated by Django 3.2.3 on 2021-05-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0008_auto_20210520_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='domyslne_konto_bakowe',
            field=models.ManyToManyField(to='fakir.KontoBankowe'),
        ),
        migrations.AddField(
            model_name='kontobankowe',
            name='wlasciciel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fakir.firma'),
            preserve_default=False,
        ),
    ]
