# Generated by Django 3.2.2 on 2021-05-10 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0008_faktura_data_wystawienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='Nazwa_towaru_uslugi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='data_wystawienia',
            field=models.DateTimeField(verbose_name='Data wystawienia'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='ilosc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='kupujący',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakir.kupujacy'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='podatek',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='sprzedawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakir.sprzedawca'),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='adres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='imie',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='nazwisko',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='NIP',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='adres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='imie',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='nazwa_firmy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sprzedawca',
            name='nazwisko',
            field=models.CharField(max_length=200),
        ),
    ]
