# Generated by Django 3.2.2 on 2021-05-10 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0009_auto_20210510_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupujacy',
            name='NIP',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='PESEL',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
