# Generated by Django 3.2.3 on 2021-05-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0009_auto_20210520_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='domyslne_konto_bakowe',
            field=models.ManyToManyField(blank=True, null=True, to='fakir.KontoBankowe'),
        ),
        migrations.RemoveField(
            model_name='kontobankowe',
            name='wlasciciel',
        ),
        migrations.AddField(
            model_name='kontobankowe',
            name='wlasciciel',
            field=models.ManyToManyField(to='fakir.Firma'),
        ),
    ]
