# Generated by Django 3.2.2 on 2021-05-10 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0010_auto_20210510_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='J_M',
            field=models.CharField(choices=[('1', 'Godzina'), ('2', 'Sztuka')], default='2', max_length=200, verbose_name='J.N'),
        ),
        migrations.AlterField(
            model_name='kupujacy',
            name='NIP',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
