# Generated by Django 3.2.3 on 2021-05-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0010_auto_20210520_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='domyslne_konto_bakowe',
        ),
        migrations.AddField(
            model_name='firma',
            name='domyslne_konto_bakowe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakir.kontobankowe'),
        ),
    ]
