# Generated by Django 3.2.3 on 2021-05-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0012_auto_20210520_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='domyslne_konto_bakowe',
            new_name='domyslne_konto_bankowe',
        ),
    ]
