# Generated by Django 3.2 on 2021-05-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0012_auto_20210510_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='licznik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fakir.licznikfaktur'),
        ),
    ]
