# Generated by Django 3.2 on 2021-05-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0013_faktura_licznik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='J_M',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='Nazwa_towaru_uslugi',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='ilosc',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='podatek',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='wartosc_netto',
        ),
        migrations.AddField(
            model_name='faktura',
            name='nazwa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='licznikfaktur',
            name='nazwa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='licznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakir.licznikfaktur'),
        ),
        migrations.CreateModel(
            name='PozycjaFaktur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_towaru_uslugi', models.CharField(max_length=200)),
                ('J_M', models.CharField(choices=[('1', 'Godzina'), ('2', 'Sztuka')], default='2', max_length=200, verbose_name='J.M')),
                ('ilosc', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wartosc_netto', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakir.faktura')),
            ],
        ),
    ]
