# Generated by Django 3.2 on 2021-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakir', '0014_auto_20210510_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='wartosc_brutto',
        ),
        migrations.AddField(
            model_name='pozycjafaktur',
            name='wartosc_brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
